<dt>Wave</dt>
<dd><%wave.num%>/<%wave.max%></dd>
<dt>Difficulty</dt>
<dd><%rules.difficulty.text%></dd>
<dt>Players</dt>
<dd><%rules.numplayers%>/<%rules.maxplayers%></dd>
<dt>Minimum to Start</dt>
<dd><%rules.minnetplayers%></dd>
<dt>Spectators</dt>
<dd><%rules.numspectators%>/<%rules.maxspectators%></dd>
<dt>Player Map Voting</dt>
<dd><%rules.mapvote%></dd>
<dt>Player Kick voting</dt>
<dd><%rules.kickvote%></dd>
