<style type="text/css">
	#fastnav{ position: absolute; top: 40px; left: 430px; }
	#fastnav a { margin-right: 6px; padding: 4px 6px; border: 1px solid #a5181a; text-decoration: none; }
	#fastnav a:hover{ background: #4c1111; }
</style>

<div id="fastnav">
  <a href="http://127.0.0.1:8080/ServerAdmin/current/info">Example 1</a>
  <a href="http://127.0.0.1:8082/ServerAdmin/current/info">Example 2</a>
  <a href="http://127.0.0.1:8084/ServerAdmin/current/info">Example 3</a>
</div>